env:
  node: true
  commonjs: true
  mocha: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules: { "no-unused-vars": ["error", { argsIgnorePattern: "next" }] }
