name: remote_container
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx:alpine
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - name: docker-test
        run: npm run docker-test